name: Build and Push Docker Images

on:
  push:
    tags:
      - 'mn-v*'
      - 'ms-v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract tag info
        id: taginfo
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          PREFIX="${TAG%%-*}"
          VERSION="${TAG#*-}"
          echo "prefix=$PREFIX" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Load tag map
        id: tagmap
        run: |
          DIR=$(jq -r .${{ steps.taginfo.outputs.prefix }} tag-map.json)
          echo "dir=$DIR" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ${{ steps.tagmap.outputs.dir }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ steps.tagmap.outputs.dir }}:${{ steps.taginfo.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ steps.tagmap.outputs.dir }}:latest
          platforms: linux/amd64,linux/arm64
